# Generated by Django 4.1.3 on 2022-11-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urdu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Please input model title.", max_length=64
                    ),
                ),
                (
                    "published",
                    models.BooleanField(verbose_name="Is this test model published."),
                ),
                (
                    "is_demo",
                    models.BooleanField(help_text="Is this a demo test model?"),
                ),
            ],
        ),
    ]
