# Generated by Django 4.1.3 on 2022-11-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urdu", "0002_testmodel"),
    ]

    operations = [
        migrations.DeleteModel(name="TestModel",),
        migrations.AddField(
            model_name="school",
            name="language_to_learn",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="school",
            name="native_country",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="school",
            name="native_language",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="school",
            name="Class",
            field=models.IntegerField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="school",
            name="roll_no",
            field=models.IntegerField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="school",
            name="section",
            field=models.IntegerField(default="", max_length=50),
        ),
    ]
