# Generated by Django 4.1.3 on 2022-11-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urdu", "0007_alter_school_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="photo",
            field=models.FileField(default="", upload_to="myimage"),
        ),
    ]
