# Generated by Django 4.1.3 on 2022-11-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urdu", "0008_alter_school_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school", name="Class", field=models.IntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="school", name="roll_no", field=models.IntegerField(default=""),
        ),
    ]
