# Generated by Django 4.1.3 on 2022-11-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urdu", "0009_alter_school_class_alter_school_roll_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="Class",
            field=models.CharField(default="", max_length=50),
        ),
    ]
