# Generated by Django 4.1.3 on 2022-11-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urdu", "0010_alter_school_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="roll_no",
            field=models.CharField(default="", max_length=50),
        ),
    ]
