# Generated by Django 4.1.3 on 2022-11-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urdu", "0013_alter_madarsa_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="madarsa",
            name="photo",
            field=models.ImageField(default="", upload_to="madarsa"),
        ),
    ]
