# Generated by Django 4.1.3 on 2022-11-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urdu", "0016_alter_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.CharField(default="", max_length=50),
        ),
    ]
